title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-03
owner: ucsb-cs156-f24
repo_name: team02-f24-03
pull_requests: [{"author":{"id":"U_kgDOBtPjyQ","is_bot":false,"login":"ChristopherChau","name":"Christopher Chau"},"headRefName":"articles_e2e_tests","number":125,"title":"Articles e2e tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/125"},{"author":{"id":"U_kgDOBtPjyQ","is_bot":false,"login":"ChristopherChau","name":"Christopher Chau"},"headRefName":"articles_integration_tests","number":124,"title":"Articles integration tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/124"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-IT","number":123,"title":"Eugene it","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/123"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"chloe-webIT","number":120,"title":"UCSBDiningCommonsMenuItem End to End Test","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/120"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"chloe-03","number":119,"title":"UCSBDiningCommonsMenuItem IT","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/119"}]
