title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-03
owner: ucsb-cs156-f24
repo_name: team02-f24-03
pull_requests: [{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"Bharat-HelpRequest-EditPage","number":112,"title":"Bharat help request edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/112"},{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"Bharat-HelpRequest-IndexPage","number":111,"title":"Bharat help request index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/111"},{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"Bharat-HelpRequest-CreatePage","number":110,"title":"Bharat help request create page","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/110"},{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"Bharat-HelpRequest-CopyPlaceholders","number":108,"title":"Finished Copying the Placeholders","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/108"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue23","number":107,"title":"Eugene issue23","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/107"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue24","number":106,"title":"Eugene issue24","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/106"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue22","number":105,"title":"Eugene issue22","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/105"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue21","number":100,"title":"Eugene issue21","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/100"},{"author":{"id":"U_kgDOBtzY9A","is_bot":false,"login":"pballani","name":""},"headRefName":"priyanka-issue32","number":92,"title":"Priyanka issue32","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/92"},{"author":{"id":"U_kgDOBtzY9A","is_bot":false,"login":"pballani","name":""},"headRefName":"priyanka-issue33","number":89,"title":"Priyanka issue33","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/89"}]
