title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-03
owner: ucsb-cs156-f24
repo_name: team02-f24-03
pull_requests: [{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"Bharat-HelpRequest-IT","number":135,"title":"Bharat Integration Tests Help Request","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/135"},{"author":{"id":"U_kgDOBtzY9A","is_bot":false,"login":"pballani","name":""},"headRefName":"priyanka-team03","number":134,"title":"integration test recommendation request","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/134"}]
