
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-03
owner: ucsb-cs156-f24
repo_name: team02-f24-03
pull_requests: [{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue18","number":65,"title":"Eugene issue18","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/65"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue17","number":63,"title":"UCSBOrg issue 17","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/63"},{"author":{"id":"U_kgDOBtPjyQ","is_bot":false,"login":"ChristopherChau","name":"Christopher Chau"},"headRefName":"articles-54","number":62,"title":"Articles 54","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/62"},{"author":{"id":"U_kgDOBtPjyQ","is_bot":false,"login":"ChristopherChau","name":"Christopher Chau"},"headRefName":"chris-issue53","number":61,"title":"Closes #53: Moved all the backend CRUD API calls","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/61"}]
