
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-03
owner: ucsb-cs156-f24
repo_name: team02-f24-03
pull_requests: [{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue18","number":72,"title":"Eugene issue18","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/72"},{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"Bharat-HelpRequest-CreateFixtures","number":71,"title":"Created Fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/71"},{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"Bharat-HelpRequest-CopyCRUDfiles","number":70,"title":"Adding files for Backend CRUD API HelpRequest","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/70"},{"author":{"id":"U_kgDOBtzY9A","is_bot":false,"login":"pballani","name":""},"headRefName":"priyanka-issue27","number":69,"title":"Priyanka issue27","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/69"},{"author":{"id":"U_kgDOBtzY9A","is_bot":false,"login":"pballani","name":""},"headRefName":"priyanka-issue26","number":68,"title":"backend crud","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/68"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"chloe-fixtures","number":67,"title":"UCSBDiningCommonsMenuItem Fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/67"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"chloe","number":66,"title":"Added team01 DiningCommonsMenuItem files","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/66"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue17","number":63,"title":"UCSBOrg issue 17","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/63"},{"author":{"id":"U_kgDOBtPjyQ","is_bot":false,"login":"ChristopherChau","name":"Christopher Chau"},"headRefName":"articles-54","number":62,"title":"Articles 54","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/62"}]
