title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/team02-f24-03
owner: ucsb-cs156-f24
repo_name: team02-f24-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzMTg5MjU5","is_bot":false,"login":"SameerSRao","name":"Sameer Rao"},"headRefName":"Sameer-MenuItemReview-E2E","number":129,"title":"Added E2E Tests for MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/129"},{"author":{"id":"MDQ6VXNlcjQzMTg5MjU5","is_bot":false,"login":"SameerSRao","name":"Sameer Rao"},"headRefName":"Sameer-MenuItemReview-Integration","number":128,"title":"Added Integration Test for MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team02-f24-03/pull/128"}]
